version: '3.8'

services:
  backend:
    build:
      context: .  # Updated from ./backend to .
    ports:
      - "8000:8000"
    environment:
      - PRIMARY_API_URL=https://api.example.com
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
