services:
  - type: web
    name: adam-alpha-api
    runtime: python
    buildCommand: pip install -r requirements.lock.txt
    startCommand: uvicorn backend.api.main:app --host=0.0.0.0 --port=8000
    envVars:
      - key: PORT
        value: 8000
      - key: API_USER
        value: admin
      - key: API_PASS_HASH
      - key: JWT_SECRET
        value: supersecret