groups:
  - name: system_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          description: "CPU usage is above 80% for 5 minutes"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: "Memory usage is above 85% for 5 minutes"

      - alert: HighAPILatency
        expr: rate(zion_request_latency_seconds_sum[5m]) / rate(zion_request_latency_seconds_count[5m]) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High API latency detected
          description: "Average API latency is above 2 seconds"

      - alert: HighErrorRate
        expr: rate(zion_requests_total{status=~"5.."}[5m]) / rate(zion_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: "Error rate is above 5% in the last 5 minutes"