```python
"""empty message

Revision ID: 001_initial
Revises: 
Create Date: 2023-10-05 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###

    from sqlalchemy.sql import text
    conn = op.get_bind()
    conn.execute(
        text("""
        INSERT INTO users (username, hashed_password, is_active, is_superuser)
        VALUES ('test_e2e_user', :hashed_password, true, false)
        ON CONFLICT (username) DO NOTHING
        """),
        {"hashed_password": "<hashed_password_for_test_user>"}
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
```