name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
    
    - name: Run tests
      run: |
        pytest --cov=backend --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v2

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t zion-api .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Render
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RENDER_HOST }}
        username: ${{ secrets.RENDER_USERNAME }}
        key: ${{ secrets.RENDER_SSH_KEY }}
        script: |
          cd /var/www/zion-api
          git pull origin main
          docker-compose -f deploy/docker-compose.yml up -d --build